--VALIDAR ESSAS DUAS TABELAS ANTES DE INTEGRAR 

--NESSA TABELA O CAMPO D3_OBSERVA DEVE ESTAR VAZIO PARA REALIZAR A INTEGRAÇÃO DE FORMA CORRETA, CASO ESTEJA PREENCHIDO DEVE ENVIAR AO TARCISIO PARA TRATATIVA
SELECT D3_OBSERVA, D3_ZCTRATK,*

--BEGIN TRAN  UPDATE D3 SET D_E_L_E_T_ = '*',R_E_C_D_E_L_ = R_E_C_N_O_
--COMMIT

FROM SD3010 D3

WHERE 
D3_ESTORNO = ''
AND D_E_L_E_T_ = ''
AND D3_FILIAL = '0102'
AND D3_EMISSAO BETWEEN '20230801' AND '20230831'
AND D3_TM  not LIKE '%998%'
AND D3_OBSERVA = 'ORIGEM.PLEA001'  


--NESSA TABELA OS CAMPOS C2_DATPRF E C2_DATRF DEVEM ESTAR VAZIOS TAMBEM, CASO CONTRARIO ENVIAR AO TARCISIO PARA ELE SETAR '0' NESSES CAMPOS
SELECT C2_DATPRF,C2_DATRF,C2_ZCTRATK,*

--COMMIT
--BEGIN TRAN UPDATE C2 SET C2_DATPRF ='',C2_DATRF = ''

FROM SC2010

WHERE C2_FILIAL = '0102' 
--AND C2_ZCTRATK like '281379914%'
AND C2_PRODUTO <> 'MANUTENCAO' --COLOCAR ISSO POIS PRODUTOS COM ESSE STATUS SÃO OS's, E EU NÃO POSSO MATA-LAS POIS SÃO OUTROS PROCESSOS
AND C2_EMISSAO BETWEEN '20230801' AND '20230831'
AND C2_DATRF <> '' 
AND D_E_L_E_T_ = ''